language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env: DB=mysql

before_script:
  - mkdir app/cache
  - chmod 777 app/cache
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:update --force
  - php app/console doctrine:fixtures:load --no-interaction

script: phpunit -c app

after_failure: 
  - cat app/logs/test.log

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
