# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.myagileproduct.org
baseurl: 
title: my agile product
author: Francois-Xavier Soubirou
email: your-email@domain.com
description: >
  my agile product is an open source software to manage functional 
  features of a product by the description of scenarios.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
exclude: [nbproject]

gems:
- jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Download
    icon: cloud-download
    url: https://github.com/jfx/my-agile-product/releases
  - title: Demo
    icon: laptop
    url: /demo
  - title: github
    icon: github
    url: https://github.com/jfx/my-agile-product
