bln-ftree_child:
    pattern:  /child
    defaults: { _controller: "Map3FeatureBundle:Tree:child", _format: json }

bln-ftree_node:
    pattern:  /node/{nid}
    defaults: { _controller: "Map3FeatureBundle:Tree:node" }
    options:
        expose: true

bln-ftree_del:
    pattern:  /del/{nid}
    defaults: { _controller: "Map3FeatureBundle:Tree:del", _format: json }
    options:
        expose: true
