bln-ftree_children:
    pattern:  /children
    defaults: { _controller: "Map3FeatureBundle:Tree:children", _format: json }

bln-ftree_node:
    pattern:  /node
    defaults: { _controller: "Map3FeatureBundle:Tree:node" }

bln-ftree_del:
    pattern:  /del/{nid}
    defaults: { _controller: "Map3FeatureBundle:Tree:del", _format: json }
    options:
        expose: true
