baseline_view:
    pattern:  /{id}
    defaults: { _controller: "Map3BaselineBundle:Baseline:view" }

baseline_add:
    pattern:  /add/{id}
    defaults: { _controller: "Map3BaselineBundle:Baseline:add" }

baseline_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "Map3BaselineBundle:Baseline:edit" }

baseline_del:
    pattern:  /del/{id}
    defaults: { _controller: "Map3BaselineBundle:Baseline:del" }
