imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        cookie_lifetime: ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
        version:    %app.version%
        build:      %app.build%
        formatDate: %app.formatDate%
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
#    bundles:        [ ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        lessphp:
             file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
             apply_to: "\.less$"
        cssembed:
             jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
             apply_to: "\.css$|\.less$"
        yui_css:
             jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
             apply_to: "\.css$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:         "%database_driver%"
        host:           "%database_host%"
        port:           "%database_port%"
        server_version: "%database_version%"
        dbname:         "%database_name%"
        user:           "%database_user%"
        password:       "%database_password%"
        charset:        UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
# Bootstrap bundle
mopa_bootstrap:
    form: ~
    menu: ~
    icons:
        icon_set: glyphicons
        shortcut: icon
    
# FOSUser bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Map3\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        form:
            type: map3_resettingformtype
        email:
            template: Map3UserBundle:User:resetting.email.html.twig

parameters:
    app.version:               0.6.0
    app.build:                 BBB
    app.formatDate:            dd/mm/yyyy
    app.codeCoverage: false
    app.defaultPasswordLength: 12
