map3_scenario:
    resource: "@Map3ScenarioBundle/Resources/config/routing.yml"
    prefix:   /

map3_baseline:
    resource: "@Map3BaselineBundle/Resources/config/routing.yml"
    prefix:   /

map3_core:
    resource: "@Map3CoreBundle/Resources/config/routing.yml"
    prefix:   /

map3_dashboard:
    resource: "@Map3DashboardBundle/Resources/config/routing.yml"
    prefix:   /

map3_feature:
    resource: "@Map3FeatureBundle/Resources/config/routing.yml"
    prefix:   /

map3_product:
    resource: "@Map3ProductBundle/Resources/config/routing.yml"
    prefix:   /

map3_release:
    resource: "@Map3ReleaseBundle/Resources/config/routing.yml"
    prefix:   /

map3_user:
    resource: "@Map3UserBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"