map3_product:
    resource: "@Map3ProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

map3_pdt-user:
    resource: "@Map3ProductBundle/Resources/config/routing/user.yml"
    prefix:   /pdt-user

pdt-release_index:
    pattern:  /releases/{id}
    defaults: { _controller: "Map3ProductBundle:Release:index" }
    requirements:
        id:  \d+
