map3_product:
    resource: "@Map3ProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

map3_pdt-user:
    resource: "@Map3ProductBundle/Resources/config/routing/user.yml"
    prefix:   /pdt-user

map3_pdt-release:
    resource: "@Map3ProductBundle/Resources/config/routing/release.yml"
    prefix:   /pdt-release
