parameters:
#    map3_product.example.class: Map3\ProductBundle\Example

services:
#    map3_product.example:
#        class: %map3_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
