parameters:
#    map3_user.example.class: Map3\UserBundle\Example

services:
#    map3_user.example:
#        class: %map3_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
