parameters:

services:
    map3_user.updatecontext4user:
        class: Map3\UserBundle\Service\UpdateContext4User
        arguments: [ '@security.context', '@doctrine.orm.entity_manager', '@fos_user.user_manager', '@logger' ]
        tags:
            - { name: monolog.logger, channel: uctx }
        scope: request

    map3_user.AuthenticationListener:
        class: Map3\UserBundle\Service\AuthenticationListener
        arguments: [ '@doctrine.orm.entity_manager', '@fos_user.user_manager' ]
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onSecurityAuthenticationSuccess }

    map3_user.passwordFactory:
        class: Map3\UserBundle\Service\PasswordFactory
        arguments: [ '%app.defaultPasswordLength%' ]
        scope: request

    map3_user.resetting.form.type:
        class: Map3\UserBundle\Form\Type\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: map3_resettingformtype }
