bln-tes_view:
    pattern:  /{id}
    defaults: { _controller: "Map3ScenarioBundle:Test:view" }

bln-tes_add:
    pattern:  /add/{nid}
    defaults: { _controller: "Map3ScenarioBundle:Test:add" }
    options:
       expose: true

bln-tes_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "Map3ScenarioBundle:Test:edit" }

bln-tes_del:
    pattern:  /del/{id}
    defaults: { _controller: "Map3ScenarioBundle:Test:del" }
