map3_bln-ftree:
    resource: "@Map3FeatureBundle/Resources/config/routing/ftree.yml"
    prefix:   /bln-ftree/{bid}
    requirements:
        bid:  \d+

map3_bln-cat:
    resource: "@Map3FeatureBundle/Resources/config/routing/category.yml"
    prefix:   /bln-cat
    requirements:
        id:  \d+

map3_bln-feat:
    resource: "@Map3FeatureBundle/Resources/config/routing/feature.yml"
    prefix:   /bln-feat
    requirements:
        id:  \d+
