release_view:
    pattern:  /{id}
    defaults: { _controller: "Map3ReleaseBundle:Release:view" }


release_add:
    pattern:  /add/{id}
    defaults: { _controller: "Map3ReleaseBundle:Release:add" }

release_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "Map3ReleaseBundle:Release:edit" }

release_del:
    pattern:  /del/{id}
    defaults: { _controller: "Map3ReleaseBundle:Release:del" }
