release_view:
    pattern:  /{id}
    defaults: { _controller: "Map3ReleaseBundle:Release:view" }
    requirements:
        id:  \d+

release_add:
    pattern:  /add
    defaults: { _controller: "Map3ReleaseBundle:Release:add" }

release_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "Map3ReleaseBundle:Release:edit" }
    requirements:
        id:  \d+

release_del:
    pattern:  /del/{id}
    defaults: { _controller: "Map3ReleaseBundle:Release:del" }
    requirements:
        id:  \d+
