map3_baseline:
    resource: "@Map3BaselineBundle/Resources/config/routing/baseline.yml"
    prefix:   /baseline

map3_bln-ref:
    resource: "@Map3BaselineBundle/Resources/config/routing/reference.yml"
    prefix:   /bln-ref
