map3_baseline:
    resource: "@Map3BaselineBundle/Resources/config/routing/baseline.yml"
    prefix:   /baseline
    requirements:
        id:  \d+

map3_bln-ref:
    resource: "@Map3BaselineBundle/Resources/config/routing/reference.yml"
    prefix:   /bln-ref
    requirements:
        id:  \d+

bln-refs_index:
    pattern:  /bln-refs/{id}
    defaults: { _controller: "Map3BaselineBundle:Reference:index" }
    requirements:
        id:  \d+

bln-features_index:
    pattern:  /bln-features/{id}
    defaults: { _controller: "Map3BaselineBundle:Feature:index" }
    requirements:
        id:  \d+
