parameters:
#    map3_baseline.example.class: Map3\BaselineBundle\Example

services:
#    map3_baseline.example:
#        class: %map3_baseline.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
