map3_release:
    resource: "@Map3ReleaseBundle/Resources/config/routing/release.yml"
    prefix:   /release
    
map3_rls-baseline:
    resource: "@Map3ReleaseBundle/Resources/config/routing/baseline.yml"
    prefix:   /rls-baseline
