map3_release:
    resource: "@Map3ReleaseBundle/Resources/config/routing/release.yml"
    prefix:   /release
    
rls-baseline_index:
    pattern:  /baselines/{id}
    defaults: { _controller: "Map3ReleaseBundle:Baseline:index" }
    requirements:
        id:  \d+
