parameters:
#    map3_release.example.class: Map3\ReleaseBundle\Example

services:
#    map3_release.example:
#        class: %map3_release.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
