services:
    map3_scenario.testService:
        class: Map3\ScenarioBundle\Service\TestService
        arguments: [ '@doctrine.orm.entity_manager' ]
        
    map3_scenario.stepHtmlformat:
        class: Map3\ScenarioBundle\Extensions\StepHtmlFormatExtension
        tags:
            - { name: twig.extension }
