pdt-user_index:
    pattern:  /
    defaults: { _controller: "Map3ProductBundle:User:index" }

pdt-user_add:
    pattern:  /add
    defaults: { _controller: "Map3ProductBundle:User:add" }

pdt-user_edit:
    pattern:  /edit/{id}
    defaults: { _controller: "Map3ProductBundle:User:edit" }
    requirements:
        id:  \d+

pdt-user_del:
    pattern:  /del/{id}
    defaults: { _controller: "Map3ProductBundle:User:del" }
    requirements:
        id:  \d+
